name: Linter

on: [push, pull_request]

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24.x'
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        default: true
        target: wasm32-unknown-unknown
    - run: npm install
    - run: npm run build
    - run: npm run lint
    - run: npm test
