name: Linter

on: [push, pull_request]

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v5
    - run: npm install
    - run: npm run build-release
    - run: npm run lint
    - run: npm test
